# Generated by Django 3.1.4 on 2020-12-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
